### ISSUE TITLE
_MAIN : TODO overview

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/DPI#29]
*If proves to do a very usefull tool then I can justify the time investment.  

# Prioritized 
## Demonstrate utilitity ! 

- [ ] 1. Comparison using assemblies same isolates, different assembly methods (short/VS long reads) : concept 
    - which variables are stabile and which ones are not (we might not have enough data but we can try)
- [ ] 2. Dimension reduction: identify the variables that least correlate with the similarity measure (eg. cgMLST)

## Reporting 
- [ ] What needs to be looked at for the different questions we want to answer

## Documentation 
- [ ] Documentation to complete - usage and problems that are not solved yet #12 (incl. tweak #31) 
- [ ] Make final organigram of the pipeline in README #15 

## Code (itself)
- [ ] data_usage_enhancement:: #17 add column group for comparisons group of pairs of isolates ? & pairs for easier linking between tables
Reasons: 
 - would be nice at the end to be able to compare all isolates believed to belong to a single epidemiological group (could do that with input reading or directly into DPI) - could go eg. in a report 
 - can make a concept first
NB:  make a list of the questions I want to answer and see what will be most actuall to add first.

- [x] data_usage_enhancement:: Adding exteranal tables to the database easily -> maybe a simple module to help to merge data into the database : as separate workflow : 

# Should be done when possible 
- [ ]  Choose which files are required for output, see #9

## code 
- [ ] simplify the defensive programming - and avoid redundancy error message. 
    - want in log of python scripts and not nf  

## Testing 
- [ ] retesting the scripts individually (scope python) to be sure works both scripts and pipeline
- [ ] test file set - incl. empy (gff ) that are not query_additional to see if pipeline detect, query_additional empty

- [ ] *unittesting python  (started ...) - need to develop the scripts

- [x] table wrangling so it can be used directly in analysis form (but first need to know exacly what will go into the report stage)

# Wont do now but on wish list

### Features 
- [ ] Connecting / adding similarity analysis results to database (eg. from ALPPACA) see #18 

- [ ] eg: issue #13 conda env for checkr -> is not running on the pipeline now but separately - ? implement ? enough to import 

### Optimisation
- [ ] improve the clarity of loggin info from the python script - there is too much info repetitive and it needs to be better structured so its easier to read. Pipe all to individual login, we do not want to appear into nf directly expect if error it needs to indicate which logfile to look at (think how to do that if its run independently vs in pipeline)

- [ ] *improve the wrangling and merging to a single database efficiency. (No time for the development version). 
    - Explore possibility to use nextflow SQL new database system eg. if the results are exported to json files ? and then imported into the SQL database via nextflow -> I do not think it will work (unless maybe export results as json ?)
    - Could also explore databases system that allow read write in parallel to shorten the process of creating tables and putting them into the database ... eg. mariaDB osv 
    - Then all tables could be exported to mysqlite database for portability. NB: will require importing original sqlite to other db system to be able to add new data if necessary
    - Data could be merged eg on csv files and then imported in database, but then need to export data first if exist - I think writing directly in good db would be best, with a DB that can work in parallel for writing.
- [ ] rewrite merging DB script - needs to be better and more efficient (but depends on solution choosen)
- [ ] *benchmarking and adjusting parameters for optimized speed. 
- [ ] make a separate config file for conda and containers ? so can be updated more easily?  #14 (closed now) - update and adjust conda containers #35
- [ ] make process name visible when running on SAGA -> update config ? modules
